config/routes.rb
Rails.application.routes.draw do

  
  devise_for :voters

  root 'welcome#index'

  resources :candidates do
    resources :comments
    member do
      get 'vote'
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
 	#@candidates = Candidate.all
 	if voter_signed_in? 
 		redirect_to candidates_path
 	else
 		redirect_to voter_session_path
 	end
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
 <h1>Welcome#index</h1>
 <p>Find me in app/views/welcome/index.html.erb</p>
<%=link_to("LOG IN" , voter_session_path , :method => :get) %>
<%=link_to("LOG Out" , destroy_voter_session_path , :method => :delete) %>

<%= link_to("Sign Up", new_voter_registration_path) %>

<%= render 'devise/sessions/new'%>

    <!-- <div class="form">
      
      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup">   
          <h1>Sign Up for Free</h1>
          
          <form action="/" method="post">
          
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" />
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <button type="submit" class="button button-block"/>Get Started</button>
          
          </form>

        </div>
        
        <div id="login">   
          <h1>Welcome Back!</h1>
          
          <form action="/" method="post">
          
            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot"><a href="#">Forgot Password?</a></p>
          
          <button class="button button-block"/>Log In</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> -->