config/routes.rb
Rails.application.routes.draw do

  
  devise_for :voters

  root 'welcome#index'

  resources :candidates do
    resources :comments
    member do
      get 'vote'
    end
  end

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	has_many :voters
	has_many :comments


	max_paginates_per 100

	has_attached_file :image
	
	validates :name, presence: true, uniqueness: true
	validates :plan, presence: true
	validates :loaction, presence: true

	validates_attachment :image,
                  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]
 #before_action :adminication , except: [:vote]


  # GET /candidates
  # GET /candidates.json
  def index
    
    @page = params[:page]

    @candidates = Candidate.page(@page)
    #@users = User.order(:name).page 3
   # @count = Voter.where(candidate_id => @can)

   @voter_all = Voter.all.count


  end

              
  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @page= params[:page]
  @comment = Comment.new
  @c = Comment.where('candidate_id' => @candidate.id).page(@page)
  end


  def vote
    #byebug

    if current_voter.candidate_id == nil
    current_voter.candidate_id =  params[:id]
    current_voter.save
  end
     redirect_to candidates_path
  end


  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :plan, :loaction, :image)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :plan %><br>
    <%= f.text_area :plan %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :loaction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<div class="navbar navbar-default" , style="background:#d9edf7"> 
        <ul class="col-md-2">
        <h4>Hello, <%= current_voter.email %></h4>
      </ul>
<ul class="nav nav-pills col-md-2" style="float:right">      
  <li role="presentation" class="active"><%= link_to 'Home', candidates_path , :class=> "btn btn-primary "%></li>
  <li role="presentation" class="active">  <%=link_to("Log Out" , destroy_voter_session_path , :method => :delete , :class=> "btn btn-primary" ,:style=>"float:right") %></li>

</ul>
       </div>

<div class="jombotron container">
  <%= paginate @candidates%>
    <% @candidates.each do |candidate| %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title", style="font-size:36px;"><%= candidate.name %></h3>
    <h6 style="font-size:16px;"><%= link_to 'Profile' ,candidate %></h6>
  </div>
  <div class="panel-body">
    
       
  <div class="progress">

  <%- percent = (Voter.where('candidate_id' => candidate.id).length.to_f / @voter_all.to_f) * 100 %>
  <%- width = "width:#{percent}%" %>
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style=<%= width %> >
  <%= Voter.where('candidate_id' => candidate.id).length%> / <%= @voter_all %>
  </div>
</div>
<div class="alert alert-success" role="alert">
          PLAN :  <%= candidate.plan %>
          </div>


  <% if current_voter.id == 1%>
       
        <%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } , :class=> "btn btn-danger",:style=>"float:right" %>

<%end%>
      
       <% if current_voter.candidate == nil %>
          <button type="button" class="btn btn-success" style="float:left">  <%= link_to 'Vote' ,  vote_candidate_path(candidate.id) %> </td> </button>
        <%end%>


  </div>
</div>        
    <% end %>

<% if current_voter.id == 1 %>
<%= link_to 'New Candidate', new_candidate_path %>
<%end%>
</div>

app/views/candidates/new.html.erb
<div class= "jombotron container">
	<div class="panel panel-info" >
    	<div class="panel-heading">
    		 <div class="form-horizontal">

<h1>New Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>
</div>
</div>
</div>
</div>

app/views/candidates/show.html.erb
<div class="navbar navbar-default" , style="background:#d9edf7"> 
        <ul class="col-md-2">
        <h4>Hello, <%= current_voter.email %></h4>
      </ul>
<ul class="nav nav-pills col-md-2" style="float:right">      
  <li role="presentation" class="active"><%= link_to 'Home', candidates_path , :class=> "btn btn-primary "%></li>
  <li role="presentation" class="active">  <%=link_to("Log Out" , destroy_voter_session_path , :method => :delete , :class=> "btn btn-primary" ,:style=>"float:right") %></li>

</ul>
       </div>

<p id="notice"><%= notice %></p>

<div class="jombotron container-fluid row">
<div class="col-md-4">


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-body">

<%=image_tag(@candidate.image.url , :class => "img_responsive img-circle center-block" , :style=> "width:160px; height:160px; align-content:center")%>
  
  </div>

  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">
    <div class="glyphicon glyphicon-user"></div>
        <strong >Name:</strong>
          <%= @candidate.name %>
        </li>
    <li class="list-group-item">
    <div class="glyphicon glyphicon-flag"></div>
     <strong>Plan:</strong>
  <%= @candidate.plan %>

  </li>
    <li class="list-group-item">
    <div class="glyphicon glyphicon-home"></div>
      <strong>Location:</strong>
        <%= @candidate.loaction %>
    </li>
  </ul>
</div>

</div>
<div class="col-md-8">


<%= form_for([@candidate,@comment]) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-inline form-group field col-md-10">

        <%= f.text_area :content, :class=>"form-control fixed" ,cols: 90, rows:1,  :placeholder=>"Your comments" %>
        <%= f.hidden_field :candidate_id ,value: @candidate.id %>

        <%= f.hidden_field :voter_id, value: current_voter.id%>


        <%= f.submit  :value=> "SAY IT" ,:class=>"form-control action btn btn-primary  "  %>
      </div>
<% end %>


<div class ="col-md-10">

<%= paginate @c %>
<% @c.each do |comment| %>

   <div class="panel panel-primary">
  <div class="panel-body">
  <%- @email = Voter.find(comment.voter_id).email%>
        <b><%= @email %> :</b>
        	<span style="width:auto">
  	<%= time_ago_in_words(comment.created_at)%> ago</span>

  </div>
  <div class="panel-footer">
  	<p class=""><%= comment.content %> </p> 
  

  </div>
</div>


<%end%>



<%link_to 'Edit', edit_candidate_path(@candidate)%>
</div>

</div>

<%#= link_to 'Edit', edit_candidate_path(@candidate) %> 